import type { CurriculumDefinition } from "@/server/curriculum/types";

/**
 * ČESKÝ JAZYK A LITERATURA – BETA
 * Source of truth for seed — not rendered by UI directly.
 * Linked to ingested DOCX via sourceFilenames.
 */
export const cjlBetaDefinition: CurriculumDefinition = {
  definitionVersion: 1,
  subject: {
    slug: "cesky-jazyk-a-literatura",
    title: "Český jazyk a literatura",
    description: "Maturitní příprava ČJL — beta corpus.",
    status: "published",
  },
  curriculum: {
    slug: "cjl-beta",
    title: "Český jazyk a literatura – BETA",
    description:
      "První beta curriculum z importovaných maturitních DOCX. Topic dependency graph řídí doporučené pořadí učení.",
    targetExam: "maturita-cjl",
    status: "published",
    version: 1,
  },
  modules: [
    {
      slug: "jazyk",
      code: "A",
      title: "Jazyk",
      summary: "Lexikologie: homonyma, mnohoznačnost, synonyma, antonyma.",
      orderIndex: 0,
      status: "published",
      topics: [
        {
          slug: "homonyma",
          title: "Homonyma",
          summary: "Stejná forma, různé významy — homonyma vs. polysémie.",
          orderIndex: 0,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Co jsou to homonyma x slova mnohoznačná.docx"],
          prerequisiteSlugs: [],
        },
        {
          slug: "slova-mnohoznacna",
          title: "Slova mnohoznačná",
          summary: "Polysémie — jedno slovo, více souvisejících významů.",
          orderIndex: 1,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Co jsou to homonyma x slova mnohoznačná.docx"],
          prerequisiteSlugs: ["homonyma"],
        },
        {
          slug: "synonyma",
          title: "Synonyma",
          summary: "Slova blízkého významu a stylové rozdíly.",
          orderIndex: 2,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Co jsou to homonyma x slova mnohoznačná.docx"],
          prerequisiteSlugs: ["homonyma"],
        },
        {
          slug: "antonyma",
          title: "Antonyma",
          summary: "Opak významu — typy antonym.",
          orderIndex: 3,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Co jsou to homonyma x slova mnohoznačná.docx"],
          prerequisiteSlugs: ["synonyma"],
        },
        {
          slug: "rozdily-a-rozpoznavani",
          title: "Rozdíly a praktické rozpoznávání",
          summary:
            "Jak rozlišit homonyma, polysémii, synonyma a antonyma v praxi.",
          orderIndex: 4,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Co jsou to homonyma x slova mnohoznačná.docx"],
          prerequisiteSlugs: [
            "homonyma",
            "slova-mnohoznacna",
            "synonyma",
            "antonyma",
          ],
        },
      ],
    },
    {
      slug: "literarni-smery",
      code: "B",
      title: "Literární směry",
      summary: "Romantismus → realismus → kritický realismus → naturalismus.",
      orderIndex: 1,
      status: "published",
      topics: [
        {
          slug: "romantismus",
          title: "Romantismus",
          summary: "Hlavní znaky romantismu a kontext.",
          orderIndex: 0,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Romantismus - hl. znaky.docx"],
          prerequisiteSlugs: [],
        },
        {
          slug: "realismus",
          title: "Realismus",
          summary: "Obecné znaky realismu.",
          orderIndex: 1,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["1. Realismus.docx"],
          prerequisiteSlugs: ["romantismus"],
        },
        {
          slug: "kriticky-realismus",
          title: "Kritický realismus",
          summary: "Angažovaný pohled, sociální konflikty, náprava.",
          orderIndex: 2,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["1. Realismus.docx"],
          prerequisiteSlugs: ["realismus"],
        },
        {
          slug: "naturalismus",
          title: "Naturalismus",
          summary: "Krajní směr realismu — dědičnost a prostředí.",
          orderIndex: 3,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["1. Realismus.docx"],
          prerequisiteSlugs: ["kriticky-realismus"],
        },
      ],
    },
    {
      slug: "narodni-obrozeni",
      code: "C",
      title: "Národní obrození",
      summary: "Kontext, periodizace, osobnosti, jazyk, kultura, rukopisy.",
      orderIndex: 2,
      status: "published",
      topics: [
        {
          slug: "no-historicky-kontext",
          title: "Historický kontext",
          summary: "Politické a kulturní pozadí národního obrození.",
          orderIndex: 0,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: [],
        },
        {
          slug: "no-periodizace",
          title: "Periodizace",
          summary: "Fáze národního obrození.",
          orderIndex: 1,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-historicky-kontext"],
        },
        {
          slug: "no-osobnosti",
          title: "Osobnosti",
          summary: "Klíčové osobnosti obrození.",
          orderIndex: 2,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-periodizace"],
        },
        {
          slug: "no-jazykoveda",
          title: "Jazykověda",
          summary: "Jazyková kodifikace a obrana češtiny.",
          orderIndex: 3,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-historicky-kontext"],
        },
        {
          slug: "no-novinarstvi",
          title: "Novinářství",
          summary: "Periodický tisk a publicistika v obrození.",
          orderIndex: 4,
          examRelevance: "medium",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-osobnosti"],
        },
        {
          slug: "no-divadlo",
          title: "Divadlo",
          summary: "Divadelní život národního obrození.",
          orderIndex: 5,
          examRelevance: "medium",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-osobnosti"],
        },
        {
          slug: "no-rukopisy",
          title: "Rukopisy",
          summary: "Rukopis královédvorský a zelenohorský — kontext a spor.",
          orderIndex: 6,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-periodizace"],
        },
        {
          slug: "no-historie",
          title: "Historie",
          summary: "Historické psaní a vlastenecká historiografie.",
          orderIndex: 7,
          examRelevance: "medium",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-historicky-kontext"],
        },
        {
          slug: "no-poezie",
          title: "Poezie",
          summary: "Obrozenská poezie a přechod k romantismu.",
          orderIndex: 8,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["Národní obrození v Čechách.docx"],
          prerequisiteSlugs: ["no-osobnosti", "romantismus"],
        },
      ],
    },
    {
      slug: "svetovy-realismus",
      code: "D",
      title: "Světový realismus",
      summary: "Francie, Anglie, Rusko a další autoři.",
      orderIndex: 3,
      status: "published",
      topics: [
        {
          slug: "realismus-francie",
          title: "Francie",
          summary: "Balzac, Flaubert, Zola, Maupassant a další.",
          orderIndex: 0,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["2. Realismus ve Francii.docx"],
          prerequisiteSlugs: ["realismus", "naturalismus"],
        },
        {
          slug: "realismus-anglie",
          title: "Anglie",
          summary: "Dickens a anglický realismus.",
          orderIndex: 1,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["4. Realismus v Anglii a další autoři.docx"],
          prerequisiteSlugs: ["realismus"],
        },
        {
          slug: "realismus-rusko",
          title: "Rusko",
          summary: "Gogol, Tolstoj, Dostojevskij a ruský realismus.",
          orderIndex: 2,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["3. Realismus v Rusku.docx"],
          prerequisiteSlugs: ["kriticky-realismus"],
        },
        {
          slug: "realismus-dalsi-autori",
          title: "Další autoři",
          summary: "Sienkiewicz, Twain a další světoví realisté.",
          orderIndex: 3,
          examRelevance: "medium",
          status: "published",
          sourceFilenames: ["4. Realismus v Anglii a další autoři.docx"],
          prerequisiteSlugs: ["realismus"],
        },
      ],
    },
    {
      slug: "ceska-literatura-a-drama",
      code: "E",
      title: "Česká literatura a drama",
      summary: "Němcová, Jirásek, realistické drama 2. poloviny 19. století.",
      orderIndex: 4,
      status: "published",
      topics: [
        {
          slug: "nemcova-babicka",
          title: "Božena Němcová / Babička",
          summary: "Autorka a dílo Babička v kontextu české literatury.",
          orderIndex: 0,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Babička.docx"],
          prerequisiteSlugs: ["romantismus", "realismus", "no-osobnosti"],
        },
        {
          slug: "jirasek",
          title: "Alois Jirásek",
          summary: "Historická próza a dramatická tvorba.",
          orderIndex: 1,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["11. A. Jirásek.docx"],
          prerequisiteSlugs: ["realismus", "no-historie"],
        },
        {
          slug: "ceske-realisticke-drama",
          title: "České realistické drama",
          summary: "Přehled českého realistického dramatu 2. pol. 19. stol.",
          orderIndex: 2,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["12. České drama 2. pol 19. stol.docx"],
          prerequisiteSlugs: ["realismus"],
        },
        {
          slug: "stroupeznicky",
          title: "Stroupežnický",
          summary: "Ladislav Stroupežnický — Naši furianti (po QA korekci dat).",
          orderIndex: 3,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["12. České drama 2. pol 19. stol.docx"],
          prerequisiteSlugs: ["ceske-realisticke-drama"],
        },
        {
          slug: "preissova",
          title: "Preissová",
          summary: "Gabriela Preissová — Gazdina roba, Její pastorkyňa.",
          orderIndex: 4,
          examRelevance: "high",
          status: "published",
          sourceFilenames: ["12. České drama 2. pol 19. stol.docx"],
          prerequisiteSlugs: ["ceske-realisticke-drama"],
        },
        {
          slug: "mrstikove-marysa",
          title: "Bratři Mrštíkové / Maryša",
          summary: "Maryša — sociální drama z jihomoravské vesnice.",
          orderIndex: 5,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["12. České drama 2. pol 19. stol.docx"],
          prerequisiteSlugs: ["ceske-realisticke-drama"],
        },
      ],
    },
    {
      slug: "rozbory-del",
      code: "F",
      title: "Rozbory děl",
      summary: "Maturitní rozbory: Máj, Kytice, Babička.",
      orderIndex: 5,
      status: "published",
      topics: [
        {
          slug: "rozbor-maj",
          title: "Máj",
          summary: "Rozbor Máje K. H. Máchy.",
          orderIndex: 0,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Máj.docx"],
          prerequisiteSlugs: ["romantismus", "no-poezie"],
        },
        {
          slug: "rozbor-kytice",
          title: "Kytice",
          summary: "Rozbor Kytice K. J. Erbena.",
          orderIndex: 1,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Kytice.docx"],
          prerequisiteSlugs: ["romantismus", "no-poezie"],
        },
        {
          slug: "rozbor-babicka",
          title: "Babička",
          summary: "Rozbor Babičky Boženy Němcové.",
          orderIndex: 2,
          examRelevance: "critical",
          status: "published",
          sourceFilenames: ["Babička.docx"],
          prerequisiteSlugs: ["nemcova-babicka"],
        },
      ],
    },
  ],
};
