import { deterministicUuid } from "@/server/curriculum/ids";
import {
  parseTimelinePack,
  type TimelinePack,
} from "@/domain/learning/timeline";

const NS = "dammaturu.timeline";

function eid(key: string) {
  return deterministicUuid(NS, key);
}

/**
 * Literary history timeline: NO → romantismus → realismus + authors/works.
 * Years follow standard periodization from ČJL beta corpus (NO 4 etapy, etc.).
 */
export function buildLiterarniHistorieTimeline(
  now = new Date().toISOString(),
): TimelinePack {
  const pack = {
    id: eid("pack:literarni-historie"),
    slug: "literarni-historie",
    title: "Časová osa — literární historie",
    summary:
      "Národní obrození, romantismus, realismus, autoři a díla. Zoom, filtry, učení i řazení.",
    zoomPresets: [
      { id: "all", label: "Celé období", yearStart: 1770, yearEnd: 1900 },
      { id: "no", label: "Nár. obrození", yearStart: 1770, yearEnd: 1860 },
      { id: "romantismus", label: "Romantismus", yearStart: 1820, yearEnd: 1860 },
      { id: "realismus", label: "Realismus", yearStart: 1830, yearEnd: 1900 },
      { id: "1848", label: "Okolo 1848", yearStart: 1830, yearEnd: 1860 },
    ],
    events: [
      {
        id: eid("ev:josef-ii-reformy"),
        slug: "josef-ii-reformy",
        kind: "event" as const,
        title: "Osvícenské reformy (Marie Terezie / Josef II.)",
        yearStart: 1770,
        yearEnd: 1790,
        summary: "Reformy monarchie, školství, toleranční patent, nevolnictví.",
        detail:
          "V duchu osvícenství se přebudovává habsburská monarchie. Současně sílí pozice němčiny jako úředního jazyka — klíčový kontext národního obrození.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["stav-cestiny", "obranna-etapa"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:stav-cestiny"),
        slug: "stav-cestiny",
        kind: "event" as const,
        title: "Stav češtiny — hluboký úpadek",
        yearStart: 1770,
        yearEnd: 1780,
        summary: "Čeština u lidu; spisovná podoba neustálena; germanizace.",
        detail:
          "Němčina je jazykem úředním i vyšších vrstev. Češtinu používá venkov a chudší městské vrstvy. Spisovná čeština není ustálena.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["obranna-etapa"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:obranna-etapa"),
        slug: "obranna-etapa",
        kind: "movement" as const,
        title: "1. etapa NO — obranná",
        yearStart: 1770,
        yearEnd: 1805,
        summary: "Základy jazyka, literatury, divadla, novinářství.",
        detail:
          "Od 70. let 18. stol. do počátku 19. stol. Dominují klasicismus a osvícenství. Cíl: zachovat češtinu a položit základy národní literatury.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["dobrovsky", "bouda"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:dobrovsky"),
        slug: "dobrovsky",
        kind: "author" as const,
        title: "Josef Dobrovský",
        yearStart: 1753,
        yearEnd: 1829,
        summary: "Zakladatel vědecké slavistiky a bohemistiky.",
        detail:
          "Filolog, historik, teolog; evropská vědecká autorita. Klíčová postava obranné / učenecké fáze národního obrození.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["obranna-etapa"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:bouda"),
        slug: "bouda",
        kind: "event" as const,
        title: "Vlastenecké divadlo Bouda",
        yearStart: 1786,
        yearEnd: 1789,
        summary: "Dřevěné divadlo na Koňském trhu (1786–1789).",
        detail:
          "Od 1786 původní české hry (např. Thám). Bouda na dnešním Václavském náměstí; později finanční problémy a demolice.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["obranna-etapa"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:utok-etapa"),
        slug: "utok-etapa",
        kind: "movement" as const,
        title: "2. etapa NO — útok / jazykový program",
        yearStart: 1800,
        yearEnd: 1830,
        summary: "Dokázat rovnocennost češtiny evropským literaturám.",
        detail:
          "Národní hnutí přechází do útoku. Vytváří se jazykový program; v literatuře preromantismus.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["dobrovsky", "romantismus"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:romantismus"),
        slug: "romantismus",
        kind: "movement" as const,
        title: "Romantismus",
        yearStart: 1820,
        yearEnd: 1850,
        summary: "Cit, individualita, konflikt jedince a společnosti.",
        detail:
          "V českém kontextu silně v 3. etapě NO (cca 1830–1848). Typické znaky: subjektivita, příroda, národní minulost, výjimečný hrdina.",
        eras: ["romantismus", "narodni-obrozeni"],
        relatedSlugs: ["macha", "maj", "erben", "kytice"],
        sourceHint: "Romantismus - hl. znaky.docx",
      },
      {
        id: eid("ev:macha"),
        slug: "macha",
        kind: "author" as const,
        title: "Karel Hynek Mácha",
        yearStart: 1810,
        yearEnd: 1836,
        summary: "Vrcholný český romantik; autor Máje.",
        detail:
          "Představitel 3. etapy NO / romantismu. Máj (1836) je klíčové maturitní dílo.",
        eras: ["romantismus", "narodni-obrozeni"],
        relatedSlugs: ["maj", "romantismus"],
        sourceHint: "Máj.docx / NO",
      },
      {
        id: eid("ev:maj"),
        slug: "maj",
        kind: "work" as const,
        title: "Máj (Mácha)",
        yearStart: 1836,
        yearEnd: 1836,
        summary: "Lyrickoepická báseň — vina, příroda, čas.",
        detail:
          "1836. Základní text českého romantismu; motivy lásky, trestu, přírody a plynutí času.",
        eras: ["romantismus"],
        relatedSlugs: ["macha", "romantismus"],
        sourceHint: "Máj.docx",
      },
      {
        id: eid("ev:erben"),
        slug: "erben",
        kind: "author" as const,
        title: "Karel Jaromír Erben",
        yearStart: 1811,
        yearEnd: 1870,
        summary: "Autor Kytice; folklor a balady.",
        detail:
          "Představitel obrozenecké / romantické linie. Kytice spojuje lidovou tradici s moralitou a baladickou formou.",
        eras: ["romantismus", "narodni-obrozeni"],
        relatedSlugs: ["kytice"],
        sourceHint: "Kytice.docx / NO",
      },
      {
        id: eid("ev:kytice"),
        slug: "kytice",
        kind: "work" as const,
        title: "Kytice (Erben)",
        yearStart: 1853,
        yearEnd: 1853,
        summary: "Sbírka balad z lidové slovesnosti.",
        detail:
          "1853. Maturitní rozbor: vina, trest, mateřství, nadpřirozeno v lidovém rámci.",
        eras: ["romantismus"],
        relatedSlugs: ["erben"],
        sourceHint: "Kytice.docx",
      },
      {
        id: eid("ev:1848"),
        slug: "rok-1848",
        kind: "event" as const,
        title: "Rok 1848 — austroslavismus",
        yearStart: 1848,
        yearEnd: 1848,
        summary: "Palacký; politický program Slovanů v monarchii.",
        detail:
          "Politická reprezentace v čele s F. Palackým vystoupila s austroslavismem — svazek rovnoprávných národů; Čechy jako autonomní celek.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["palacky"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:palacky"),
        slug: "palacky",
        kind: "author" as const,
        title: "František Palacký",
        yearStart: 1798,
        yearEnd: 1876,
        summary: "Historik, politik; austroslavismus.",
        detail:
          "Zakladatel novodobého českého dějepisectví; Dějiny národu českého; hlasatel austroslavismu.",
        eras: ["narodni-obrozeni"],
        relatedSlugs: ["rok-1848"],
        sourceHint: "Národní obrození v Čechách.docx",
      },
      {
        id: eid("ev:realismus"),
        slug: "realismus",
        kind: "movement" as const,
        title: "Realismus",
        yearStart: 1830,
        yearEnd: 1900,
        summary: "Střízlivý obraz skutečnosti bez idealizace.",
        detail:
          "Reakce na romantismus a společenské změny. Všední hrdina, detail prostředí, sociální kauzalita. Navazuje kritický realismus a naturalismus.",
        eras: ["realismus"],
        relatedSlugs: ["kriticky-realismus", "naturalismus", "nemcova"],
        sourceHint: "1. Realismus.docx",
      },
      {
        id: eid("ev:kriticky"),
        slug: "kriticky-realismus",
        kind: "movement" as const,
        title: "Kritický realismus",
        yearStart: 1840,
        yearEnd: 1900,
        summary: "Zobrazení + kritika společenských křivd.",
        detail:
          "Angažovaný pohled na skutečnost; sociální konflikty; volání po nápravě.",
        eras: ["realismus"],
        relatedSlugs: ["realismus"],
        sourceHint: "1. Realismus.docx",
      },
      {
        id: eid("ev:naturalismus"),
        slug: "naturalismus",
        kind: "movement" as const,
        title: "Naturalismus",
        yearStart: 1860,
        yearEnd: 1900,
        summary: "Determinismus — dědičnost a prostředí (Zola).",
        detail:
          "Krajní směr realismu: člověk jako výsledek biologie a prostředí.",
        eras: ["realismus"],
        relatedSlugs: ["realismus", "zola"],
        sourceHint: "1. Realismus.docx / Francie",
      },
      {
        id: eid("ev:nemcova"),
        slug: "nemcova",
        kind: "author" as const,
        title: "Božena Němcová",
        yearStart: 1820,
        yearEnd: 1862,
        summary: "Autorka Babičky; přechod k realismu.",
        detail:
          "Významná postava české literatury 19. stol.; Babička spojuje idylu s realistickým pohledem na venkov.",
        eras: ["realismus", "romantismus"],
        relatedSlugs: ["babicka", "realismus"],
        sourceHint: "Babička.docx",
      },
      {
        id: eid("ev:babicka"),
        slug: "babicka",
        kind: "work" as const,
        title: "Babička (Němcová)",
        yearStart: 1855,
        yearEnd: 1855,
        summary: "Obraz venkova; babička jako morální střed.",
        detail:
          "1855. Maturitní dílo: prostředí Starého bělidla, konflikty, idyla vs. realita.",
        eras: ["realismus"],
        relatedSlugs: ["nemcova"],
        sourceHint: "Babička.docx",
      },
      {
        id: eid("ev:jirasek"),
        slug: "jirasek",
        kind: "author" as const,
        title: "Alois Jirásek",
        yearStart: 1851,
        yearEnd: 1930,
        summary: "Historická próza a drama.",
        detail:
          "Český realistický / historický autor; maturitní téma v beta corpusu.",
        eras: ["realismus"],
        relatedSlugs: ["realismus"],
        sourceHint: "11. A. Jirásek.docx",
      },
      {
        id: eid("ev:zola"),
        slug: "zola",
        kind: "author" as const,
        title: "Émile Zola",
        yearStart: 1840,
        yearEnd: 1902,
        summary: "Francouzský naturalismus.",
        detail:
          "Představitel naturalismu ve Francii — determinismus prostředí a dědičnosti.",
        eras: ["realismus"],
        relatedSlugs: ["naturalismus", "realismus-francie"],
        sourceHint: "2. Realismus ve Francii.docx",
      },
      {
        id: eid("ev:dickens"),
        slug: "dickens",
        kind: "author" as const,
        title: "Charles Dickens",
        yearStart: 1812,
        yearEnd: 1870,
        summary: "Anglický sociální realismus města.",
        detail:
          "Klíčový autor realismu v Anglii — sociální realita města a chudoby.",
        eras: ["realismus"],
        relatedSlugs: ["realismus"],
        sourceHint: "4. Realismus v Anglii a další autoři.docx",
      },
      {
        id: eid("ev:dostojevskij"),
        slug: "dostojevskij",
        kind: "author" as const,
        title: "F. M. Dostojevskij",
        yearStart: 1821,
        yearEnd: 1881,
        summary: "Ruský realismus — psychologie a morálka.",
        detail:
          "Představitel ruského realismu; psychologie postav a morální konflikty.",
        eras: ["realismus"],
        relatedSlugs: ["realismus"],
        sourceHint: "3. Realismus v Rusku.docx",
      },
      {
        id: eid("ev:marysa"),
        slug: "marysa",
        kind: "work" as const,
        title: "Maryša (bratři Mrštíkové)",
        yearStart: 1894,
        yearEnd: 1894,
        summary: "Sociální drama jihomoravské vesnice.",
        detail:
          "1894. Realistické drama: nerovné manželství, bohatství vs. cit.",
        eras: ["realismus"],
        relatedSlugs: ["realismus"],
        sourceHint: "12. České drama 2. pol 19. stol.docx",
      },
    ],
    createdAt: now,
    updatedAt: now,
  };

  return parseTimelinePack(pack);
}
